//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDepartment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserAccount> UserAccountSet { get; set; }
        public DbSet<Discipline> DisciplineSet { get; set; }
        public DbSet<Specialty> SpecialtySet { get; set; }
        public DbSet<Plan> PlanSet { get; set; }
        public DbSet<Group> GroupSet { get; set; }
        public DbSet<Schedule> ScheduleSet { get; set; }
        public DbSet<ScheduleWeek> ScheduleWeekSet { get; set; }
    }
}
