//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDepartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.ScheduleWeek = new HashSet<ScheduleWeek>();
            this.Group = new HashSet<Group>();
        }
    
        public int Id { get; set; }
        public int Term { get; set; }
        public int LecturesSum { get; set; }
        public int LabsSum { get; set; }
        public int PracticesSum { get; set; }
        public int ExamWorksSum { get; set; }
        public string Classroom { get; set; }
    
        public virtual ICollection<ScheduleWeek> ScheduleWeek { get; set; }
        public virtual ICollection<Group> Group { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
