// <auto-generated />
namespace MVCDepartment.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class wtf_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wtf_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201311261350317_wtf_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
