//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MVCDepartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        [DisplayName("Название предмета")]
        public string Name { get; set; }
    
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
