//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCDepartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [ScaffoldColumn(false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [DisplayName("Шифр")]
        public string Name { get; set; }
        [DisplayName("Курс")]
        [Range(1, 6,
            ErrorMessage = "Номер курса от 1 до 6")]
        public int Course { get; set; }
    
        public virtual Specialty Specialty { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
